---
- name: Construct an EC2 instance for the defined purpose
  hosts: 127.0.0.1
  user : root
  gather_facts: false

  tasks:
  
  - name: Launch EC2 Instance
    local_action:
      module: ec2
      state:  present
      keypair: "{{ keypair }}"
      group_id: "{{ securityGroup.group_id }}"
      region: "{{ region }}"
      #@TODO VPC
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ ec2_instance_type }}"
      # Name the Instance in the AWS control panel.
      instance_tags: '{ "Name": "{{ purpose }}", "ansible_group": "{{ inf_ansible_group }}", "Purpose": "{{ purpose}}" }'
      image: "{{ image }}"
      count: "{{ count }}"
      wait: yes
      state: present
    register: ec2
  
  - name: Add the new instance to the group {{ inf_ansible_group }}
    # Short Syntax.
    # Update the dynamic group listing with the current instance alias. 
    # Groupname format matches what ec2.py returns to list out the various tags.
    local_action: add_host hostname="{{ item.public_ip }}" groupname="tag_ansible_group_{{ inf_ansible_group }}"
    with_items: ec2.instances 
   
  - name: Wait for the instances to boot by checking the ssh port
    local_action: wait_for host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances
    